<?php 
return [
        [
            'sort'=>'Admin',
            'name'=>'基础管理',
            'icon'=>'layui-icon-util',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'在线聊天',
                    'url' =>url('/admin/Admin/web_chat'),
                    'icon'=>'',
                    'isShow'=>1,
                    'hasSub'=>0,
                    'state'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'在线测评',
                    'url' =>url('/admin/Admin/evaluation_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'hasSub'=>0,
                    'state'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'系统消息',
                    'url' =>url('/admin/Admin/system_mess'),
                    'icon'=>'',
                    'isShow'=>0,
                    'hasSub'=>0,
                    'state'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'个人资料',
                    'url' =>url('/admin/Admin/admin_info'),
                    'icon'=>'',
                    'isShow'=>1,
                    'hasSub'=>0,
                    'state'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'修改密码',
                    'url' =>url('/admin/System/update_pass'),
                    'icon'=>'',
                    'isShow'=>1,
                    'hasSub'=>0,
                    'state'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'锁屏密码',
                    'url' =>url('/admin/System/clock_pass'),
                    'icon'=>'',
                    'isShow'=>1,
                    'hasSub'=>0,
                    'state'=>0,
                    'author'=>0,
                ]
                
            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'任务管理',
            'icon'=>'layui-icon-log',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'待办事项',
                    'url' =>url('/admin/Todolist/todo_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>0,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'已办事项',
                    'url' =>url('/admin/Todolist/todone_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'权限管理',
            'icon'=>'layui-icon-password',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'管理员列表',
                    'url' =>url('/admin/Admin/admin_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'角色管理',
                    'url' =>url('/admin/Admin/role_group_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'权限资源',
                    'url' =>url('/admin/Admin/role_resource_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'管理员日志',
                    'url' =>url('/admin/Admin/admin_log'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'系统管理',
            'icon'=>'layui-icon-set',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'基础设置',
                    'url' =>url('/admin/System/base_info'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'背景设置',
                    'url' =>url('/admin/Point/index'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'发布公告',
                    'url' =>url('/admin/System/add_system_message'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'系统日志',
                    'url' =>url('/admin/System/system_log'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'数据可视化',
                    'url' =>url('/admin/System/echarts'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'数据库备份',
                    'url' =>url('/admin/System/backups'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'测评管理',
            'icon'=>'layui-icon-survey',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'试卷列表',
                    'url' =>url('/admin/Evaluation/examination_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'添加试卷',
                    'url' =>url('/admin/Evaluation/examination_add'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'试题列表',
                    'url' =>url('/admin/Evaluation/questions_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'添加试题',
                    'url' =>url('/admin/Evaluation/questions_add'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'插件管理',
            'icon'=>'layui-icon-component',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'插件列表',
                    'url' =>url('/admin/Plug/list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'微信管理',
            'icon'=>'layui-icon-login-wechat',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'基础配置',
                    'url' =>url('/admin/Wechat/base_config'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'菜单配置',
                    'url' =>url('/admin/Wechat/menu_custom'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'粉丝列表',
                    'url' =>url('/admin/Wechat/fans_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'模板消息',
                    'url' =>url('/admin/Wechat/template_message'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'素材管理',
                    'url' =>url('/admin/Wechat/material_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'图文素材',
                    'url' =>url('/admin/Wechat/material_news_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'数据字典',
            'icon'=>'layui-icon-template',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'字典列表',
                    'url' =>url('/admin/Dictionary/data_dictionary'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
            ]
        ],
        [
            'sort'=>'Admin',
            'name'=>'回收站',
            'icon'=>'layui-icon-delete',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'已删文章',
                    'url' =>url('/admin/Recycle/delete_article_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'已删会员',
                    'url' =>url('/admin/Recycle/delete_member_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'已删订单',
                    'url' =>url('/admin/Recycle/delete_order_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'已删测评',
                    'url' =>url('/admin/Recycle/delete_evaluation_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'会员管理',
            'icon'=>'layui-icon-user',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'会员列表',
                    'url' =>url('/admin/Member/member_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'会员类型',
                    'url' =>url('/admin/Member/member_type'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'文章管理',
            'icon'=>'layui-icon-read',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'文章列表',
                    'url' =>url('/admin/Article/article_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'添加文章',
                    'url' =>url('/admin/Article/article_add'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'分类管理',
            'icon'=>'layui-icon-tree',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'分类列表',
                    'url' =>url('/admin/Cate/cate_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'品牌管理',
            'icon'=>'layui-icon-star',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'品牌列表',
                    'url' =>url('/admin/Brand/brand_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'广告管理',
            'icon'=>'layui-icon-carousel',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'广告列表',
                    'url' =>url('/admin/Ad/ad_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'广告位置',
                    'url' =>url('/admin/Ad/position_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'商品管理',
            'icon'=>'layui-icon-cart',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'商品列表',
                    'url' =>url('/admin/Shop/shop_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'商品模型',
                    'url' =>url('/admin/Shop/model_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'订单管理',
            'icon'=>'layui-icon-cart-simple',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'订单列表',
                    'url' =>url('/admin/Order/index'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Shop',
            'name'=>'评论管理',
            'icon'=>'layui-icon-dialogue',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'评论列表',
                    'url' =>url('/admin/Comment/comment_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]
            ]
        ],
        [
            'sort'=>'Hr',
            'name'=>'部门管理',
            'icon'=>'layui-icon-user',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'公司部门',
                    'url' =>url('/admin/Department/department_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Hr',
            'name'=>'招聘管理',
            'icon'=>'layui-icon-camera',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'招聘列表',
                    'url' =>url('/admin/Recruit/recruit_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'发布招聘',
                    'url' =>url('/admin/Recruit/add_recruit'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Hr',
            'name'=>'差勤管理',
            'icon'=>'layui-icon-video',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'考勤打卡',
                    'url' =>url('/admin/Attendance/clock'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'考勤记录',
                    'url' =>url('/admin/Attendance/attendance_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'请假记录',
                    'url' =>url('/admin/Attendance/leave_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'请假类型',
                    'url' =>url('/admin/Attendance/leave_type'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'出差记录',
                    'url' =>url('/admin/Attendance/business_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Hr',
            'name'=>'员工管理',
            'icon'=>'layui-icon-username',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'电子档案',
                    'url' =>url('/admin/Staff/archives_list'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Hr',
            'name'=>'工资管理',
            'icon'=>'layui-icon-rmb',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'工资基本项',
                    'url' =>url('/admin/Wage/basic_item'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'工资扣除项',
                    'url' =>url('/admin/Wage/deduction'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'工资绩效项',
                    'url' =>url('/admin/Wage/performance_item'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ],
                [
                    'name'=>'工资年终项',
                    'url' =>url('/admin/Wage/bonuses'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Hr',
            'name'=>'报表管理',
            'icon'=>'layui-icon-read',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'考勤报表',
                    'url' =>url('/admin/Report/attendance_report'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ],
        [
            'sort'=>'Finance',
            'name'=>'财务管理',
            'icon'=>'layui-icon-dollar',
            'isShow'=>1,
            'state'=>1,
            'hasSub'=>1,
            'author'=>0,
            'sub'=>[
                [
                    'name'=>'现金管理',
                    'url' =>url('/admin/Rinance/cash'),
                    'icon'=>'',
                    'isShow'=>1,
                    'state'=>1,
                    'hasSub'=>0,
                    'author'=>0,
                ]

            ]
        ]
        
    ]


 ?>